export class PFile {
    icon: any = '';
    name: string = 'My Box';
    size: number = 0;
    id: number = 0;
    uid: string = '0';
    mine_type: string = '';
    links: any[] = [];
    count: number = 0;
    path: string = '/';
    parent_uid: string = '0';
    parent: number = 0;
    kind: string = 'Folder';
    permissions: string = '';
    file_access?: string = '';
    data?: any[] = [];
    copy_count: number = 0;
    has_copy: number = 0;
    is_dir: number = 0;
    is_hosted: number = 0;
    is_inbin: number | boolean = 0;
    is_starred: number = 0;
    revision: string = '';
    user_id: number = 0;
    drive: string = '';
    owner: string = '';
    updated_at: string = '';
    created_at: string = '';
    image: string = '';
    extension: string = '';
    file_url: string = '';
    file_content: any = '';
    format: any = '';
    prev_name?: string;
    isSelected?: boolean = false;
    custom_name?: string;
    mouse_event?: string = 'null';
}
